FROM frolvlad/alpine-oraclejdk8:slim
ADD ["target/inventory-service-1.0.0-SNAPSHOT.jar", "app.jar"]
EXPOSE 8182 8787
ENV JAVA_OPTS="-Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8787,suspend=n"
RUN sh -c 'touch /app.jar'
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=docker -jar /app.jar" ]